
-----------------
---Crea tablas---
-----------------

--Crea tabla employees
CREATE TABLE EMPLOYEES(
ID NUMBER (*,0) PRIMARY KEY NOT NULL,
MANAGER_ID NUMBER (*,0),
DATE_OF_JOINING DATE NOT NULL,
FULL_NAME VARCHAR2 (255) NOT NULL,

CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
);

--Crea tabla projects
CREATE TABLE PROJECTS(
ID NUMBER (*,0) PRIMARY KEY NOT NULL,
CODE VARCHAR2 (255) NOT NULL,
MANAGER_ID NUMBER (*,0) NOT NULL,
BUDGET NUMBER (10,2) NOT NULL,
DATE_OF_BEGINNING DATE,
DATE_OF_ENDING DATE,

CONSTRAINT FK_MANAGER_PROJECT FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)

);

--Crea tabla salaries
CREATE TABLE SALARIES(
ID NUMBER (*,0) PRIMARY KEY NOT NULL,
EMPLOYEE_ID NUMBER (*,0) NOT NULL,
PROJECT_ID NUMBER (*,0),
SALARY NUMBER (10,2) NOT NULL CHECK (SALARY > 500), 

CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);

---------------
---Consultas---
---------------
--  Write a SQL query to count the number of employees working in project '44905736599'
--Escriba una consulta SQL para contar el número de empleados que trabajan en el proyecto '44905736599'
SELECT COUNT(EMPLOYEES.FULL_NAME)
FROM EMPLOYEES
  INNER JOIN PROJECTS ON EMPLOYEES.id = PROJECTS.MANAGER_ID
WHERE PROJECTS.CODE ='44905736599';

--  Write a SQL query to fetch employee names (one column, don't change the alias) having salary greater than or equal to 1000 and less than or equal 2500.
--Escriba una consulta SQL para buscar nombres de empleados (una columna, no cambie el alias) que tengan un salario mayor o igual a 1000 y menor o igual a 2500.
SELECT EMPLOYEES.FULL_NAME
FROM EMPLOYEES
  INNER JOIN SALARIES ON EMPLOYEES.id = SALARIES.EMPLOYEE_ID
WHERE SALARIES.SALARY >=1000 OR SALARIES.SALARY <=2500;
