
-----------------
---Crea tablas---
-----------------

--Crea tabla employees
CREATE TABLE EMPLOYEES(
ID NUMBER (*,0) PRIMARY KEY NOT NULL,
MANAGER_ID NUMBER (*,0),
DATE_OF_JOINING DATE NOT NULL,
FULL_NAME VARCHAR2 (255) NOT NULL,

CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
);

--Crea tabla projects
CREATE TABLE PROJECTS(
ID NUMBER (*,0) PRIMARY KEY NOT NULL,
CODE VARCHAR2 (255) NOT NULL,
MANAGER_ID NUMBER (*,0) NOT NULL,
BUDGET NUMBER (10,2) NOT NULL,
DATE_OF_BEGINNING DATE,
DATE_OF_ENDING DATE,

CONSTRAINT FK_MANAGER_PROJECT FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)

);

--Crea tabla salaries
CREATE TABLE SALARIES(
ID NUMBER (*,0) PRIMARY KEY NOT NULL,
EMPLOYEE_ID NUMBER (*,0) NOT NULL,
PROJECT_ID NUMBER (*,0),
SALARY NUMBER (10,2) NOT NULL CHECK (SALARY > 500), 

CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);
